{% set name = "bubblewrap" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/containers/bubblewrap/archive/refs/tags/v{{ version }}.tar.gz
  sha256: cfeeb15fcc47d177d195f06fdf0847e93ee3aa6bf46f6ac0a141fa142759e2c3

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - automake
    - autoconf
    - make
    - pkgconfig
    - libtool
  host:
    - libcap

test:
  commands:
    - bwrap --help

about:
  home: https://github.com/containers/bubblewrap
  license: LGPL-2.0-or-later
  license_file: COPYING
  summary: Unprivileged sandboxing tool

extra:
  recipe-maintainers:
    - wolfv
