{% set name = "bubblewrap" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/containers/bubblewrap/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2b21ee6d2bead1aaf7c35742e5e53b061ec6eb1644889a4379fda662b03e8121

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - automake
    - autoconf
    - make
    - pkgconfig
    - libtool
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - libcap

test:
  commands:
    - bwrap --help

about:
  home: https://github.com/containers/bubblewrap
  license: LGPL-2.0-or-later
  license_file: COPYING
  summary: Unprivileged sandboxing tool

extra:
  recipe-maintainers:
    - wolfv
