{% set name = "bubblewrap" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/containers/bubblewrap/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8ede2b605d5aaf68aaa6ef1a5264ba7a31108c98417a8f88d289d0b5fa820c1b

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - automake
    - autoconf
    - make
    - pkgconfig
    - libtool
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - libcap

test:
  commands:
    - bwrap --help

about:
  home: https://github.com/containers/bubblewrap
  license: LGPL-2.0-or-later
  license_file: COPYING
  summary: Unprivileged sandboxing tool

extra:
  recipe-maintainers:
    - wolfv
