{% set name = "bubblewrap" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/containers/bubblewrap/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f434c7b6534445e3d39183d69460c274a23e33747204de3f27e89051208c4ef1

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - automake
    - autoconf
    - make
    - pkgconfig
    - libtool
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - libcap

test:
  commands:
    - bwrap --help

about:
  home: https://github.com/containers/bubblewrap
  license: LGPL-2.0-or-later
  license_file: COPYING
  summary: Unprivileged sandboxing tool

extra:
  recipe-maintainers:
    - wolfv
