context:
  name: bubblewrap
  version: 0.11.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/containers/bubblewrap/archive/refs/tags/v${{ version }}.tar.gz
  sha256: cfeeb15fcc47d177d195f06fdf0847e93ee3aa6bf46f6ac0a141fa142759e2c3

build:
  number: 0
  skip:
    - not linux
  script: |
    meson _builddir -Dselinux=disabled ${MESON_ARGS}
    meson compile -C _builddir
    meson test -C _builddir
    meson install -C _builddir

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - meson
    - ninja
  host:
    - libcap

tests:
  - script:
    - bwrap --help

about:
  homepage: https://github.com/containers/bubblewrap
  repository: https://github.com/containers/bubblewrap
  license: LGPL-2.0-or-later
  license_file: COPYING
  summary: Unprivileged sandboxing tool

extra:
  recipe-maintainers:
    - wolfv
