context:
  name: bubblewrap
  version: "0.11.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/containers/bubblewrap/archive/refs/tags/v${{ version }}.tar.gz
  sha256: fb6ebf0264dfe9fb88777d352deeedf5aecf2e36e78da148157036b647f86e0f

build:
  number: 0
  skip:
    - not linux
  script: |
    meson _builddir -Dselinux=disabled ${MESON_ARGS}
    meson compile -C _builddir
    meson test -C _builddir
    meson install -C _builddir

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - pkg-config
    - meson
    - ninja
  host:
    - libcap

tests:
  - script:
      - bwrap --help

about:
  homepage: https://github.com/containers/bubblewrap
  repository: https://github.com/containers/bubblewrap
  license: LGPL-2.0-or-later
  license_file: COPYING
  summary: Unprivileged sandboxing tool

extra:
  recipe-maintainers:
    - wolfv
